### ISSUE TITLE
Headers in POST req missing..?

### ISSUE THREAD

**Issue by TrickPixeltje** [Biitez/Byte.Library#1]
Title,

Where are they, how do I change them?
I need to add an Auth header to my post req.

**Comment by LuisGraphyFVX** [comment]
you can add them with httpRequest.AddHeader ("Header name", "content");
you must use the xNet.dll

**Comment by Biitez** [comment]
Hello, 

Sorry for the delay in answering, Now I've been on my own time and I've rewritten the whole library.
If you still need help, to add a header just go to the method where the requests are made and place:

httpRequest.AddHeader("The header name", "The header value");
